name: datadex
version: 1.0.0
config-version: 2

profile: default

target-path: target

models:
  datadex:
    +materialized: table

vars:
  'dbt_date:time_zone': 'America/Sao_Paulo'

require-dbt-version: [">=1.7.0", "<2.0.0"]
