default:
  outputs:
    dev:
      type: duckdb
      path: "../data/local.duckdb"
      extensions:
        - https
        - parquet
        - spatial
      threads: 12
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
      plugins:
        - module: excel
          config: 
            engine: "openpyxl"
            file: "/tmp/excel_file_out.xlsx"
            lazy_close: False
  target: dev

config:
  send_anonymous_usage_stats: False
  use_colors: True
