SELECT 
    DUC.SG_UF AS UF,
    DUC.CO_MUNICIPIO_IBGE AS COD_MUN,
    DUC.DT_UNIDADE_CENTRO_CUSTO AS DATA,
    EXTRACT(
        MONTH
        FROM DUC.DT_UNIDADE_CENTRO_CUSTO
    ) AS MES_CAD,
    EXTRACT(
        YEAR
        FROM DUC.DT_UNIDADE_CENTRO_CUSTO
    ) AS ANO_CAD,
    DUC.NU_CNPJ AS CNPJ_UN,
    DUC.CO_SEQ_UNIDADE_CENTRO_CUSTO AS COD_UN,
    DUC.NO_RAZAO_SOCIAL AS NM_UN,
    DUC.NO_PERSONALIZADO AS NM_P_UN,
    DTT.NO_TIPO_UNIDADE AS TIPO_UN,
    DTPREST.NO_TIPO_PRESTADOR AS TIPO_PRESTADOR,
    DUC.NU_LEITO_ATENDE
FROM {{ ref('TB_UNIDADE_CENTRO_CUSTO') }} DUC
    LEFT JOIN {{ ref('TB_TIPO_UNIDADE') }} DTT ON DUC.CO_TIPO_UNIDADE = DTT.CO_SEQ_TIPO_UNIDADE
    LEFT JOIN {{ ref('TB_TIPO_PRESTADOR') }} DTPREST ON DUC.CO_TIPO_PRESTADOR = DTPREST.CO_SEQ_TIPO_PRESTADOR
WHERE DUC.ST_REGISTRO_ATIVO = 'S'
    -- remover registros de teste
    AND DUC.CO_SEQ_UNIDADE_CENTRO_CUSTO NOT IN (3553, 4473) 
ORDER BY DATA