SELECT 
    UCC.SG_UF AS UF,
    MP.DT_PRODUCAO_CENTRO_CUSTO AS DT_PROD,
    EXTRACT(
        MONTH
        FROM MP.DT_PRODUCAO_CENTRO_CUSTO
    ) AS MES_PROD,
    EXTRACT(
        YEAR
        FROM MP.DT_PRODUCAO_CENTRO_CUSTO
    ) AS ANO_PROD,
    CC.CO_UNIDADE_CENTRO_CUSTO AS COD_UN,
    CC.CO_SEQ_CENTRO_CUSTO AS COD_CC,
    CC.NO_CENTRO_CUSTO AS NM_CC,
    CC.NO_CENTRO_CUSTO_UNIDADE AS NM_CC_UN,
    CASE
        WHEN MP.CO_TIPO_CENTRO_CUSTO = 1 THEN 'Administrativo'
        WHEN MP.CO_TIPO_CENTRO_CUSTO = 2 THEN 'Intermediario'
        WHEN MP.CO_TIPO_CENTRO_CUSTO = 3 THEN 'Externo'
        WHEN MP.CO_TIPO_CENTRO_CUSTO = 4 THEN 'Final'
    END AS TP_CC,
    TP.CO_ITEM_PRODUCAO AS COD_IP,
    IP.NO_ITEM_PRODUCAO AS NM_IP,
    TP.QT_PRODUCAO_CENTRO_CUSTO AS QT_IP,
    round_even(MC.VL_CUSTO_DIRETO,2) AS VL_CD,
    round_even(MC.VL_CUSTO_INDIRETO,2) AS VL_CI,
    round_even(MC.VL_CUSTO_TOTAL,2) AS VL_CT,
    round_even(MC.VL_CUSTO_TOTAL/ TP.QT_PRODUCAO_CENTRO_CUSTO, 2) AS VL_UNIT
FROM {{ ref('TB_MAPAREL_PRODUCAO') }} MP
    INNER JOIN {{ ref('TB_MOVIMENTACAO_CUSTO') }} MC ON MP.CO_CENTRO_CUSTO = MC.CO_CENTRO_CUSTO
    AND MP.DT_PRODUCAO_CENTRO_CUSTO = MC.DT_MOVIMENTACAO_CUSTO
    LEFT JOIN {{ ref('TB_CENTRO_CUSTO') }} CC ON MC.CO_CENTRO_CUSTO = CC.CO_SEQ_CENTRO_CUSTO
    LEFT JOIN {{ ref('TB_UNIDADE_CENTRO_CUSTO') }} UCC ON CC.CO_UNIDADE_CENTRO_CUSTO = UCC.CO_SEQ_UNIDADE_CENTRO_CUSTO
    LEFT JOIN {{ ref('TB_PRODUCAO') }} TP ON MP.CO_CENTRO_CUSTO = TP.CO_CENTRO_CUSTO
    AND MP.DT_PRODUCAO_CENTRO_CUSTO = TP.DT_PRODUCAO_CENTRO_CUSTO
    LEFT JOIN {{ ref('TB_ITEM_PRODUCAO') }} IP ON TP.CO_ITEM_PRODUCAO = IP.CO_SEQ_ITEM_PRODUCAO
WHERE MC.VL_CUSTO_TOTAL > 0
    AND TP.QT_PRODUCAO_CENTRO_CUSTO > 0
    AND TP.ST_REGISTRO_ATIVO = 'S'
    AND CC.ST_REGISTRO_ATIVO = 'S'
    AND IP.NO_ITEM_PRODUCAO <> 'Não Informado'
    -- remover registros de teste
    AND UCC.CO_SEQ_UNIDADE_CENTRO_CUSTO NOT IN (3553, 4473) 
    AND MP.DT_PRODUCAO_CENTRO_CUSTO BETWEEN '2022-03-01' AND '2024-03-01'
ORDER BY DT_PROD


