version: 2

sources:

    - name: raw
      tables:
        - name: PL_ALIM
          meta:
            external_location: "st_read('../data/raw/ALIM_JAN.xlsx')"
        - name: TB_CENTRO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_CENTRO_CUSTO202403130948.csv')"
        - name: TB_DESPESA
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_DESPESA_202403130952.csv')"
        - name: TB_TIPO_CENTRO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_TIPO_CENTRO_CUSTO_202403130957.csv')"
        - name: TB_TIPO_PRESTADOR
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_TIPO_PRESTADOR_202403130956.csv')"
        - name: TB_TIPO_UNIDADE
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_TIPO_UNIDADE_202403130955.csv')"
        - name: TB_PRODUCAO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_PRODUCAO_202403130958.csv')"
        - name: TB_ITEM_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_ITEM_CUSTO_202403130959.csv')"
        - name: TB_ITEM_PRODUCAO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_ITEM_PRODUCAO_202403131000.csv')"
        - name: TB_GRUPO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_GRUPO_CUSTO_202403131001.csv')"
        - name: TB_MAPAREL_PRODUCAO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_MAPAREL_PRODUCAO_202403131002.csv')"
        - name: TB_CRITERIO_RATEIO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_CRITERIO_RATEIO_202403131004.csv')"
        - name: TB_UNIDADE_CENTRO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_UNIDADE_CENTRO_CUSTO_202403131003.csv')"
        - name: TB_DESPESA_CENTRO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_DESPESA_CENTRO_CUSTO_202403131004.csv')"
        - name: TB_MOVIMENTACAO_CUSTO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_MOVIMENTACAO_CUSTO_202403131006.csv')"
        - name: TB_CENTRO_CUSTO_MOVIMENTACAO
          meta:
            external_location: "read_csv('../data/raw/APURASUS_TB_CENTRO_CUSTO_MOVIMENTACAO_202403131006.csv')"
          

            