SELECT
    DES.CO_UNIDADE_CENTRO_CUSTO AS COD_UN,
    MAX(DES.DT_DESPESA) AS DT_ULT,
    EXTRACT(MONTH FROM MAX(DES.DT_DESPESA)) AS MES_ULT,
    EXTRACT(YEAR FROM MAX(DES.DT_DESPESA)) AS ANO_ULT
FROM {{ source('raw', 'TB_DESPESA') }} DES
LEFT JOIN {{ source('raw', 'TB_UNIDADE_CENTRO_CUSTO') }} DUC ON DES.CO_UNIDADE_CENTRO_CUSTO = DUC.CO_SEQ_UNIDADE_CENTRO_CUSTO
WHERE DES.VL_DESPESA > 0 
    AND DUC.NO_PERSONALIZADO IS NOT NULL 
    AND DES.ST_REGISTRO_ATIVO = 'S'
GROUP BY DES.CO_UNIDADE_CENTRO_CUSTO
