SELECT
    UCC.SG_UF AS UF,
    UCC.CO_SEQ_UNIDADE_CENTRO_CUSTO AS COD_UN,
    UCC.NO_PERSONALIZADO AS NM_P_UN,
    TCC.CO_SEQ_TIPO_CENTRO_CUSTO AS TP_CC,
    TCC.NO_TIPO_CENTRO_CUSTO AS TPCC,
    CCU.CO_SEQ_CENTRO_CUSTO AS CO_CC,
    CCU.NO_CENTRO_CUSTO AS NM_CC,
    CCU.NO_CENTRO_CUSTO_UNIDADE AS NM_CC_UN,
    TCCREC.NO_TIPO_CENTRO_CUSTO AS TPCC_T,
    CCM.CO_CENTRO_CUSTO_REC AS CO_CC_T,
    CCREC.NO_CENTRO_CUSTO_UNIDADE AS NM_CC_T,
    SUM(DISTINCT(CCM.VL_MATRIZ)) AS VALOR,
    EXTRACT(MONTH FROM CCM.DT_MOVIMENTACAO) AS MES,
    EXTRACT(YEAR FROM CCM.DT_MOVIMENTACAO) AS ANO
FROM {{ source('raw', 'TB_CENTRO_CUSTO_MOVIMENTACAO') }} CCM
INNER JOIN {{ source('raw', 'TB_MAPAREL_PRODUCAO') }} MP ON CCM.CO_CENTRO_CUSTO_PROD = MP.CO_CENTRO_CUSTO AND CCM.DT_MOVIMENTACAO = MP.DT_PRODUCAO_CENTRO_CUSTO
INNER JOIN {{ source('raw', 'TB_CENTRO_CUSTO') }} CCU ON CCM.CO_CENTRO_CUSTO_PROD = CCU.CO_SEQ_CENTRO_CUSTO 
INNER JOIN {{ source('raw', 'TB_TIPO_CENTRO_CUSTO') }} TCC ON MP.CO_TIPO_CENTRO_CUSTO = TCC.CO_SEQ_TIPO_CENTRO_CUSTO 
INNER JOIN {{ source('raw', 'TB_UNIDADE_CENTRO_CUSTO') }} UCC ON CCU.CO_UNIDADE_CENTRO_CUSTO = UCC.CO_SEQ_UNIDADE_CENTRO_CUSTO
INNER JOIN {{ source('raw', 'TB_MAPAREL_PRODUCAO') }} MPREC ON CCM.CO_CENTRO_CUSTO_REC = MPREC.CO_CENTRO_CUSTO AND CCM.DT_MOVIMENTACAO = MPREC.DT_PRODUCAO_CENTRO_CUSTO
INNER JOIN {{ source('raw', 'TB_CENTRO_CUSTO') }} CCREC ON CCM.CO_CENTRO_CUSTO_REC = CCREC.CO_SEQ_CENTRO_CUSTO
INNER JOIN {{ source('raw', 'TB_TIPO_CENTRO_CUSTO') }} TCCREC ON MPREC.CO_TIPO_CENTRO_CUSTO = TCCREC.CO_SEQ_TIPO_CENTRO_CUSTO
WHERE 
    CCM.DT_MOVIMENTACAO >= '2013-01-01'
    AND CCM.DT_MOVIMENTACAO <= '2024-02-10'
    AND CCM.TP_MATRIZ = 'F' 
    AND CCU.ST_REGISTRO_ATIVO = 'S'
    AND TCC.ST_REGISTRO_ATIVO = 'S'
    AND MP.ST_REGISTRO_ATIVO = 'S'
    AND CCM.VL_MATRIZ > 0
GROUP BY 
    UCC.SG_UF,
    UCC.CO_SEQ_UNIDADE_CENTRO_CUSTO,
    UCC.NO_PERSONALIZADO,
    TCC.CO_SEQ_TIPO_CENTRO_CUSTO,
    TCC.NO_TIPO_CENTRO_CUSTO,
    CCU.CO_SEQ_CENTRO_CUSTO,
    CCU.NO_CENTRO_CUSTO,
    CCU.NO_CENTRO_CUSTO_UNIDADE,
    TCCREC.NO_TIPO_CENTRO_CUSTO,
    CCM.CO_CENTRO_CUSTO_REC,
    CCREC.NO_CENTRO_CUSTO_UNIDADE,
    CCM.DT_MOVIMENTACAO
