SELECT DISTINCT 
    TD.DT_DESPESA::DATE AS DT_DESPESA,
    TD.CO_UNIDADE_CENTRO_CUSTO,
    
    FROM {{ref('TB_DESPESA')}} TD
    INNER JOIN (
        SELECT 
            CO_UNIDADE_CENTRO_CUSTO,
            MAX(DT_DESPESA) AS MaxDT_DESPESA
        FROM {{ref('TB_DESPESA')}}
        WHERE VL_DESPESA > 0
            AND ST_REGISTRO_ATIVO = 'S'
        GROUP BY CO_UNIDADE_CENTRO_CUSTO
        ) AS MaxDates 
    ON  TD.CO_UNIDADE_CENTRO_CUSTO = MaxDates.CO_UNIDADE_CENTRO_CUSTO
    AND TD.DT_DESPESA = MaxDates.MaxDT_DESPESA
WHERE 
    TD.VL_DESPESA > 0
    AND TD.ST_REGISTRO_ATIVO = 'S'
ORDER BY TD.DT_DESPESA DESC