project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000
  render:
    - README.md
    - notebooks
    - dashboard.qmd
    - docs

format:
  html:
    anchor-sections: true
    smooth-scroll: true
    theme: litera

website:
  title: Datadex
  repo-url: https://github.com/fredguth/datadex
  repo-actions: [edit, issue]
  navbar:
    search: true
    logo: https://em-content.zobj.net/thumbs/120/google/350/package_1f4e6.png
    left:
      - text: dbt Docs
        icon: sun
        file: dbt
      - text: Knowledge Base
        icon: book
        href: notebooks
      - text: Tutorial
        icon: bi-journal
        href: docs/tutorial.html
      # - text: Reports
      #   icon: bi-journalbi-bookmark-plus
      #   href: reports
    tools:
      - icon: twitter
        href: https://twitter.com/fredguth
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/fredguth/datadex
          - text: Create an Issue
            url: https://github.com/fredguth/datadex/issues/new
